BEGIN TRANSACTION;
INSERT INTO "commande_cmd" VALUES (1,'2021-02-04 19:12:56','PASSEE',1);
INSERT INTO "commande_cmd" VALUES (2,'2021-02-01 16:25:45','ANNULEE',2);
INSERT INTO "pizza_piz" VALUES (1,'Margherita',6.99);
INSERT INTO "pizza_piz" VALUES (2,'4 fromages',10.9);
INSERT INTO "pizza_piz" VALUES (3,'Reine',8.9);
INSERT INTO "allergene_all" VALUES (1,'lactose');
INSERT INTO "ingredientPizza_igdpiz" VALUES (0,1);
INSERT INTO "ingredientPizza_igdpiz" VALUES (1,1);
INSERT INTO "ingredientPizza_igdpiz" VALUES (0,2);
INSERT INTO "ingredientPizza_igdpiz" VALUES (1,2);
INSERT INTO "ingredientPizza_igdpiz" VALUES (2,2);
INSERT INTO "ingredientPizza_igdpiz" VALUES (3,2);
INSERT INTO "ingredientPizza_igdpiz" VALUES (4,2);
INSERT INTO "ingredientPizza_igdpiz" VALUES (0,3);
INSERT INTO "ingredientPizza_igdpiz" VALUES (1,3);
INSERT INTO "ingredientPizza_igdpiz" VALUES (5,3);
INSERT INTO "ingredientPizza_igdpiz" VALUES (6,3);
INSERT INTO "pizzaCommande_pizcmd" VALUES (1,1);
INSERT INTO "pizzaCommande_pizcmd" VALUES (2,1);
INSERT INTO "pizzaCommande_pizcmd" VALUES (3,1);
INSERT INTO "pizzaCommande_pizcmd" VALUES (2,2);
INSERT INTO "allergeneIngredient_alligd" VALUES (1,1);
INSERT INTO "allergeneIngredient_alligd" VALUES (1,2);
INSERT INTO "allergeneIngredient_alligd" VALUES (1,3);
INSERT INTO "allergeneIngredient_alligd" VALUES (1,4);
INSERT INTO "utilisateur_util" VALUES (1,'Leo.Maze@etudiant.univ-brest.fr','mdpLeo','Mazé','Léo','8 addresse de Léo','SAME','01 23 45 67 89');
INSERT INTO "utilisateur_util" VALUES (2,'mdpLeo','mdpHugo','Mahé','Hugo','12 addresse d''Hugo','15 autre adresse d''Hugo','09 87 65 43 21');
INSERT INTO "carteBancaire_cb" VALUES (1,'4250 7075 1090 7511','Léo Mazé','10/2028','489',1);
INSERT INTO "carteBancaire_cb" VALUES (2,'4598 4669 9540 4038','Hugo Mahé','10/2028','137',2);
INSERT INTO "ingredient_igd" VALUES (0,'sauce tomate',NULL);
INSERT INTO "ingredient_igd" VALUES (1,'mozzarella',2);
INSERT INTO "ingredient_igd" VALUES (2,'chèvre',2);
INSERT INTO "ingredient_igd" VALUES (3,'emmental',2);
INSERT INTO "ingredient_igd" VALUES (4,'fourme d''Ambert A.O.P',2);
INSERT INTO "ingredient_igd" VALUES (5,'jambon',1.5);
INSERT INTO "ingredient_igd" VALUES (6,'champignons',1.3);
COMMIT;
